import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import type { GeneratedNote } from '../../types';
import { FileText, Plus, Search, Copy, Trash2, Check, Sparkles } from 'lucide-react';

export const NotesView: React.FC = () => {
  const { notes, courses, addNote, deleteNote, selectedCourseFilter } = useApp();

  const [selectedNote, setSelectedNote] = useState<GeneratedNote | null>(notes[0] || null);
  const [copied, setCopied] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [noteTitle, setNoteTitle] = useState('');
  const [noteCourseId, setNoteCourseId] = useState(courses[0]?.id || 'c1');
  const [noteContent, setNoteContent] = useState('');

  const filteredNotes = notes.filter(n => {
    const matchesCourse = selectedCourseFilter === 'all' || n.courseId === selectedCourseFilter;
    const matchesSearch = n.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      n.topicName.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCourse && matchesSearch;
  });

  const handleCopyMarkdown = () => {
    if (!selectedNote) return;
    navigator.clipboard.writeText(selectedNote.markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCreateNote = (e: React.FormEvent) => {
    e.preventDefault();
    if (!noteTitle.trim()) return;

    const newNote: GeneratedNote = {
      id: 'gn_' + Date.now(),
      title: noteTitle,
      courseId: noteCourseId,
      topicName: noteTitle,
      createdDate: new Date().toISOString().split('T')[0],
      tags: ['Custom Note', 'User Synthesized'],
      markdownContent: noteContent || `## 📌 Note: ${noteTitle}\nCustom study note added to library.`,
      keyTakeaways: ['Manually created note'],
      relatedMaterialIds: []
    };

    addNote(newNote);
    setSelectedNote(newNote);
    setIsModalOpen(false);
    setNoteTitle('');
    setNoteContent('');
  };

  return (
    <div className="space-y-6 pb-12">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white tracking-tight flex items-center gap-2">
            <FileText className="w-6 h-6 text-indigo-600 dark:text-indigo-400" />
            <span>AI Master Study Notes</span>
          </h2>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            Structured, concise study guides generated by AI from Feynman sessions and lecture materials.
          </p>
        </div>

        <button
          onClick={() => setIsModalOpen(true)}
          className="saas-button-primary flex items-center space-x-2 text-xs"
        >
          <Plus className="w-4 h-4" />
          <span>New Study Note</span>
        </button>
      </div>

      <div className="saas-card p-3 flex items-center space-x-3">
        <Search className="w-4 h-4 text-slate-400 ml-2 shrink-0" />
        <input
          type="text"
          placeholder="Search notes by title or topic..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full bg-transparent text-xs text-slate-900 dark:text-white placeholder-slate-400 focus:outline-none"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-4 space-y-3">
          {filteredNotes.length === 0 ? (
            <div className="saas-card p-8 text-center space-y-3">
              <FileText className="w-8 h-8 text-slate-400 mx-auto" />
              <p className="text-xs text-slate-500">No notes found matching query.</p>
            </div>
          ) : (
            filteredNotes.map((note) => {
              const course = courses.find(c => c.id === note.courseId);
              const isSelected = selectedNote?.id === note.id;
              return (
                <div
                  key={note.id}
                  onClick={() => setSelectedNote(note)}
                  className={`saas-card p-4 cursor-pointer transition-all ${
                    isSelected
                      ? 'border-indigo-500 bg-indigo-50/40 dark:bg-indigo-950/40 shadow-sm'
                      : 'hover:bg-slate-50 dark:hover:bg-slate-800/60'
                  }`}
                >
                  <div className="flex items-start justify-between">
                    <div className="space-y-1">
                      {course && (
                        <span className="saas-badge bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-300 font-mono text-[10px]">
                          {course.code}
                        </span>
                      )}
                      <h4 className="font-semibold text-xs text-slate-900 dark:text-white leading-snug line-clamp-2">
                        {note.title}
                      </h4>
                    </div>

                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        deleteNote(note.id);
                        if (selectedNote?.id === note.id) {
                          setSelectedNote(filteredNotes.find(n => n.id !== note.id) || null);
                        }
                      }}
                      className="text-slate-400 hover:text-rose-500 p-1"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>

                  <div className="flex items-center justify-between pt-3 border-t border-slate-100 dark:border-slate-800 mt-3 text-[10px] text-slate-400">
                    <span>{note.createdDate}</span>
                    <span className="text-indigo-600 dark:text-indigo-400 font-medium">{note.tags[0] || 'Master Note'}</span>
                  </div>
                </div>
              );
            })
          )}
        </div>

        <div className="lg:col-span-8">
          {selectedNote ? (
            <div className="saas-card overflow-hidden space-y-0">
              <div className="p-6 border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 flex items-center justify-between">
                <div>
                  <span className="text-[10px] text-indigo-600 dark:text-indigo-400 font-mono uppercase font-bold">
                    AI SYNTHESIZED NOTE
                  </span>
                  <h3 className="text-xl font-bold text-slate-900 dark:text-white tracking-tight mt-0.5">
                    {selectedNote.title}
                  </h3>
                </div>

                <button
                  onClick={handleCopyMarkdown}
                  className="saas-button-secondary flex items-center space-x-1.5 text-xs"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
                  <span>{copied ? 'Copied!' : 'Copy Markdown'}</span>
                </button>
              </div>

              <div className="p-6 space-y-4">
                <div className="p-5 bg-slate-50 dark:bg-slate-950 rounded-2xl border border-slate-200 dark:border-slate-800 font-mono text-xs text-slate-800 dark:text-slate-200 leading-relaxed whitespace-pre-wrap">
                  {selectedNote.markdownContent}
                </div>

                {selectedNote.keyTakeaways.length > 0 && (
                  <div className="space-y-2 pt-2">
                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">
                      Key Takeaways
                    </h4>
                    <div className="space-y-1.5">
                      {selectedNote.keyTakeaways.map((takeaway, idx) => (
                        <div key={idx} className="p-2.5 bg-indigo-50/60 dark:bg-slate-800/60 rounded-xl border border-indigo-100 dark:border-slate-700 text-xs text-indigo-900 dark:text-indigo-300 flex items-center gap-2">
                          <Sparkles className="w-3.5 h-3.5 text-indigo-500 shrink-0" />
                          <span>{takeaway}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div className="saas-card p-12 text-center space-y-3">
              <FileText className="w-10 h-10 text-slate-400 mx-auto" />
              <p className="text-xs text-slate-400">Select a note to read or create a new note.</p>
            </div>
          )}
        </div>
      </div>

      {isModalOpen && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="saas-card w-full max-w-lg p-6 space-y-4 bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800">
            <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-3">
              <h3 className="font-bold text-sm text-slate-900 dark:text-white">Create New Study Note</h3>
              <button onClick={() => setIsModalOpen(false)} className="text-slate-400 hover:text-slate-600 dark:hover:text-white">✕</button>
            </div>

            <form onSubmit={handleCreateNote} className="space-y-4 text-xs">
              <div>
                <label className="text-slate-700 dark:text-slate-300 font-medium block mb-1">Note Title *</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Master Summary: Dynamic Programming Recurrences"
                  value={noteTitle}
                  onChange={(e) => setNoteTitle(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl px-3 py-2 text-slate-900 dark:text-white focus:outline-none"
                />
              </div>

              <div>
                <label className="text-slate-700 dark:text-slate-300 font-medium block mb-1">Course</label>
                <select
                  value={noteCourseId}
                  onChange={(e) => setNoteCourseId(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl px-3 py-2 text-slate-900 dark:text-white focus:outline-none"
                >
                  {courses.map(c => (
                    <option key={c.id} value={c.id}>{c.code}: {c.name}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="text-slate-700 dark:text-slate-300 font-medium block mb-1">Markdown Content</label>
                <textarea
                  rows={6}
                  placeholder="Write or paste your markdown note..."
                  value={noteContent}
                  onChange={(e) => setNoteContent(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl p-3 text-slate-900 dark:text-white font-mono focus:outline-none"
                />
              </div>

              <div className="pt-2 flex items-center justify-end space-x-3">
                <button type="button" onClick={() => setIsModalOpen(false)} className="px-4 py-2 text-slate-400">
                  Cancel
                </button>
                <button
                  type="submit"
                  className="saas-button-primary"
                >
                  Save Note
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

